question_answerer_task:
  description: >
    Conduct a research about {topic}.
    Make sure you find any interesting and relevant information given
    the current year is 2024. After you do the research, make a detailed report.
  expected_output: >
    A JSON object containing:
    - "summary": A detailed summary of the topic.
    - "references": An array of reference URLs or titles used for research.
  agent: question_answerer

cheat_sheet_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A markdown string with:
    - A brief summary of the topic.
    - References to sources in a bullet point format.
  agent: cheat_sheet

content_ingestion_task:
  name: >
    Content Ingestion Task
  description: >
    Task to process and ingest uploaded PDF content into ChromaDB.
  inputs:
    - uploaded_files: List of uploaded PDF files to process.
  outputs:
    - A list of results indicating success or failure for each file processed.
  expected_output: >
    A list of strings indicating the ingestion result for each uploaded file.
  agent: content_ingestion_agent