question_answerer_task:
  description: >
    Conduct a research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    small summary text{topic} with refereces
  agent: question_answerer

cheat_sheet_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    small summary of the topic with refereces
  agent: cheat_sheet

content_ingestion_task:
  name: >
    Content Ingestion Task
  description: >  
    Task to process and ingest uploaded PDF content into ChromaDB.
  inputs:
    - uploaded_files
  outputs:
    - results
