question_answerer_task:
  description: >
    Conduct a detailed research on {topic}.
    Divide the findings into sections, each with a relevant header summarizing the section content.
    At the bottom of the report, include a list of references in bullet points.
    The year is 2024; ensure all information is current and relevant.
  expected_output: >
    A detailed report divided into sections with headers.
    Each section contains a summary of the findings, and references are listed in bullet points at the end with the link to the page.
  agent: question_answerer


cheat_sheet_task:
  description: >
    Review the context you got from the PDF file that was uploaded and make a one page summary of the PDF file.
    Make sure that the main part of the summary is about {topic}
  inputs:
    - uploaded_file: A PDF file.
  expected_output: >
    A one page summary of the provided file.
  agent: cheat_sheet

content_ingestion_task:
  name: >
    Content Ingestion Task
  description: >
    Task to process and ingest uploaded PDF content into ChromaDB.
  inputs:
    - uploaded_files: List of uploaded PDF files to process.
  outputs:
    - A list of results indicating success or failure for each file processed.
  expected_output: >
    A list of strings indicating the ingestion result for each uploaded file.
  agent: content_ingestion_agent